apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi
  namespace: flux-system
spec:
  releaseName: strimzi
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: "0.20.1"
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: flux-system
  interval: 5m
  values:
    installCRDs: true