apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: kafka-namespace
spec:
  releaseName: kafka
  chart:
    spec:
      chart: kafka
      version: "26.0.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  values:
    replicaCount: 1
    persistence:
      enabled: false
    zookeeper:
      enabled: true
      replicaCount: 1
      persistence:
        enabled: false
