apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: kafka
spec:
  interval: 10m
  chart:
    spec:
      chart: kafka
      version: 23.0.0
      sourceRef:
        kind: GitRepository
        name: xac
        namespace: flux-system
  values:
    replicaCount: 1
    persistence:
      enabled: false
    zookeeper:
      enabled: true
      replicaCount: 1
      persistence:
        enabled: false